import React, { useEffect, useState } from 'react';
import { Database, RefreshCw } from 'lucide-react';
import { auth } from '../firebase';

type Audit = { name: string; recordsSampled: number; candidateDateFields: string[]; candidateStatusFields: string[]; candidateRelationFields: string[]; examples: { id: string; values: Record<string, unknown> }[] };
export default function PracMappingAudit() {
  const [collections, setCollections] = useState<Audit[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const token = await auth.currentUser?.getIdToken(); const response = await fetch('/api/prac/mapping-audit', { headers: { Authorization: `Bearer ${token}` } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Unable to load mapping audit.'); setCollections(body.collections || []); setError(''); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Unable to load mapping audit.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <section className="rounded-xl border border-black/10 bg-white p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Database className="h-5 w-5 text-black/55" /><div><h2 className="text-sm font-semibold">PRAC data verification</h2><p className="text-xs text-black/45">Read-only schema and relationship audit</p></div></div><button onClick={() => void load()} className="rounded-md p-2 hover:bg-black/5" title="Refresh audit"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} /></button></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<div className="mt-4 grid gap-3 lg:grid-cols-2">{collections.map((collection) => <article key={collection.name} className="rounded-lg bg-[#f7f7f8] p-3"><div className="flex items-baseline gap-2"><strong className="text-sm">{collection.name}</strong><span className="text-xs text-black/45">{collection.recordsSampled} sampled</span></div><p className="mt-2 text-xs text-black/60">Relations: {collection.candidateRelationFields.join(', ') || 'none identified'}</p><p className="mt-1 text-xs text-black/60">Status: {collection.candidateStatusFields.join(', ') || 'none identified'}</p><p className="mt-1 text-xs text-black/60">Dates: {collection.candidateDateFields.join(', ') || 'none identified'}</p><pre className="mt-3 max-h-44 overflow-auto whitespace-pre-wrap rounded bg-white p-2 text-[11px] leading-relaxed text-black/70">{JSON.stringify(collection.examples, null, 2)}</pre></article>)}</div></section>;
}
