import React, { useRef, useState } from 'react';
import { Mic, PhoneOff, Send, Sparkles } from 'lucide-react';
import { auth, UserProfile } from '../firebase';

export default function PracOperations({ userProfile: _userProfile }: { userProfile: UserProfile }) {
  const [text, setText] = useState(''); const [messages, setMessages] = useState([{ role: 'assistant', text: 'I am Shane OS. Ask me about Pattaya Rent a Car.' }]); const [live, setLive] = useState(false); const peer = useRef<RTCPeerConnection | null>(null);
  const stop = () => { peer.current?.getSenders().forEach((sender) => sender.track?.stop()); peer.current?.close(); peer.current = null; setLive(false); };
  const voice = async () => { const token = await auth.currentUser?.getIdToken(); const session = await fetch('/api/prac/realtime-session', { method: 'POST', headers: { Authorization: `Bearer ${token}` } }).then((r) => r.json()); if (!session.clientSecret) throw new Error(session.error || 'Voice mode is unavailable.'); const pc = new RTCPeerConnection(); peer.current = pc; const audio = new Audio(); audio.autoplay = true; pc.ontrack = (e) => { audio.srcObject = e.streams[0]; }; (await navigator.mediaDevices.getUserMedia({ audio: true })).getTracks().forEach((track) => pc.addTrack(track)); const offer = await pc.createOffer(); await pc.setLocalDescription(offer); const answer = await fetch('https://api.openai.com/v1/realtime/calls', { method: 'POST', headers: { Authorization: `Bearer ${session.clientSecret}`, 'Content-Type': 'application/sdp' }, body: offer.sdp }); if (!answer.ok) throw new Error('Could not start voice mode.'); await pc.setRemoteDescription({ type: 'answer', sdp: await answer.text() }); setLive(true); };
  const send = async () => { if (!text.trim()) return; const question = text; setText(''); setMessages((m) => [...m, { role: 'user', text: question }]); const token = await auth.currentUser?.getIdToken(); const body = await fetch('/api/prac/assistant', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ question }) }).then((r) => r.json()); setMessages((m) => [...m, { role: 'assistant', text: body.answer || body.error }]); };
  return <section className="mx-auto flex min-h-[72vh] max-w-5xl flex-col overflow-hidden rounded-[2rem] border border-black/10 bg-white"><header className="flex items-center justify-between border-b p-5"><div><p className="text-xs font-bold tracking-widest text-gold">SHANE OS</p><h1 className="font-serif text-2xl">Pattaya Rent a Car</h1></div><button onClick={() => live ? stop() : void voice().catch((e) => setMessages((m) => [...m, { role: 'assistant', text: e.message }]))} className="rounded-xl bg-black p-3 text-white">{live ? <PhoneOff /> : <Mic />}</button></header><div className="flex-1 space-y-4 bg-[#fcfbf8] p-6">{messages.map((m, i) => <div key={i} className={m.role === 'user' ? 'text-right' : ''}><span className={m.role === 'user' ? 'inline-block rounded-2xl bg-black px-4 py-3 text-white' : 'inline-block max-w-[80%] rounded-2xl bg-white px-4 py-3 shadow-sm'}>{m.role === 'assistant' && <Sparkles className="mr-2 inline h-4 w-4 text-gold" />}{m.text}</span></div>)}</div><footer className="flex gap-2 border-t p-4"><input value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && void send()} className="flex-1 rounded-xl border px-4" placeholder="Message Shane OS..."/><button onClick={() => void send()} className="rounded-xl bg-black p-3 text-white"><Send /></button></footer></section>;
}
